version: "3.9"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate --noinput &&
               python manage.py index &&
               python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=redis

volumes:
  redis_data:
